(ns cxl_memory.actor
  "cxl_memory clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). CXL memory pooling / expansion fabric.

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; CxlDevice
   {:db/ident :cxl_memory.CxlDevice/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :cxl_memory.CxlDevice/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.CxlDevice/cxlVersion :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.CxlDevice/type :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.CxlDevice/capacityGb :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.CxlDevice/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.CxlDevice/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; MemoryRegion
   {:db/ident :cxl_memory.MemoryRegion/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :cxl_memory.MemoryRegion/deviceId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.MemoryRegion/sizeGb :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.MemoryRegion/interleave :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.MemoryRegion/volatile :db/valueType :db.type/boolean :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.MemoryRegion/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.MemoryRegion/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; FlitChannel
   {:db/ident :cxl_memory.FlitChannel/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :cxl_memory.FlitChannel/deviceId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.FlitChannel/lanes :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.FlitChannel/flitMode :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.FlitChannel/dataRateGtps :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.FlitChannel/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.FlitChannel/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; CoherenceDomain
   {:db/ident :cxl_memory.CoherenceDomain/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :cxl_memory.CoherenceDomain/deviceId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.CoherenceDomain/hostCount :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.CoherenceDomain/protocol :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.CoherenceDomain/biasMode :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.CoherenceDomain/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.CoherenceDomain/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; QosClass
   {:db/ident :cxl_memory.QosClass/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :cxl_memory.QosClass/deviceId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.QosClass/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.QosClass/bandwidthGbps :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.QosClass/latencyNs :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.QosClass/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.QosClass/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; HotplugEvent
   {:db/ident :cxl_memory.HotplugEvent/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :cxl_memory.HotplugEvent/deviceId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.HotplugEvent/kind :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.HotplugEvent/slot :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.HotplugEvent/status :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.HotplugEvent/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :cxl_memory.HotplugEvent/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"CxlDevice" "MemoryRegion" "FlitChannel" "CoherenceDomain" "QosClass" "HotplugEvent"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "cxl_memory: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "cxl_memory: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "cxl_memory: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── CxlDevice ────────────────────────────────────────────────────────────────
(defn create-cxl-device
  "Create a CxlDevice."
  [port data]
  (require-fields data ["name" "cxlVersion"])
  (let [id (new-id "cxl_cxl")
        e {:db/id id
           :cxl_memory.CxlDevice/id id
           :cxl_memory.CxlDevice/name (get data :name)
           :cxl_memory.CxlDevice/cxlVersion (get data :cxlVersion)
           :cxl_memory.CxlDevice/type (get data :type)
           :cxl_memory.CxlDevice/capacityGb (as-long (get data :capacityGb))
           :cxl_memory.CxlDevice/createdAt (now)
           :cxl_memory.CxlDevice/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-cxl-devices
  "List CxlDevice with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-cxl-devices port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :cxl_memory.CxlDevice/id))
         rows (apply-filters rows (:filter opts) [:cxl_memory.CxlDevice/name :cxl_memory.CxlDevice/cxlVersion :cxl_memory.CxlDevice/type :cxl_memory.CxlDevice/capacityGb])]
     (paginate rows opts))))

(defn get-cxl-device
  "Retrieve a CxlDevice by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-cxl-device port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-cxl-device
  "Update a CxlDevice; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :cxl_memory.CxlDevice/name (get data :name)]))
                   (cond-> (contains? data :cxlVersion) (conj [:db/add id :cxl_memory.CxlDevice/cxlVersion (get data :cxlVersion)]))
                   (cond-> (contains? data :type) (conj [:db/add id :cxl_memory.CxlDevice/type (get data :type)]))
                   (cond-> (contains? data :capacityGb) (conj [:db/add id :cxl_memory.CxlDevice/capacityGb (as-long (get data :capacityGb))]))
                   (conj [:db/add id :cxl_memory.CxlDevice/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-cxl-device
  "Delete a CxlDevice."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── MemoryRegion ────────────────────────────────────────────────────────────────
(defn create-memory-region
  "Create a MemoryRegion."
  [port data]
  (require-fields data ["sizeGb" "interleave"])
  (let [id (new-id "cxl_mem")
        e {:db/id id
           :cxl_memory.MemoryRegion/id id
           :cxl_memory.MemoryRegion/deviceId (get data :deviceId)
           :cxl_memory.MemoryRegion/sizeGb (as-long (get data :sizeGb))
           :cxl_memory.MemoryRegion/interleave (get data :interleave)
           :cxl_memory.MemoryRegion/volatile (as-bool (get data :volatile))
           :cxl_memory.MemoryRegion/createdAt (now)
           :cxl_memory.MemoryRegion/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-memory-regions
  "List MemoryRegion with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-memory-regions port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :cxl_memory.MemoryRegion/id))
         rows (apply-filters rows (:filter opts) [:cxl_memory.MemoryRegion/deviceId :cxl_memory.MemoryRegion/sizeGb :cxl_memory.MemoryRegion/interleave :cxl_memory.MemoryRegion/volatile])]
     (paginate rows opts))))

(defn get-memory-region
  "Retrieve a MemoryRegion by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-memory-region port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-memory-region
  "Update a MemoryRegion; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :deviceId) (conj [:db/add id :cxl_memory.MemoryRegion/deviceId (get data :deviceId)]))
                   (cond-> (contains? data :sizeGb) (conj [:db/add id :cxl_memory.MemoryRegion/sizeGb (as-long (get data :sizeGb))]))
                   (cond-> (contains? data :interleave) (conj [:db/add id :cxl_memory.MemoryRegion/interleave (get data :interleave)]))
                   (cond-> (contains? data :volatile) (conj [:db/add id :cxl_memory.MemoryRegion/volatile (as-bool (get data :volatile))]))
                   (conj [:db/add id :cxl_memory.MemoryRegion/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-memory-region
  "Delete a MemoryRegion."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── FlitChannel ────────────────────────────────────────────────────────────────
(defn create-flit-channel
  "Create a FlitChannel."
  [port data]
  (require-fields data ["lanes" "flitMode"])
  (let [id (new-id "cxl_fli")
        e {:db/id id
           :cxl_memory.FlitChannel/id id
           :cxl_memory.FlitChannel/deviceId (get data :deviceId)
           :cxl_memory.FlitChannel/lanes (as-long (get data :lanes))
           :cxl_memory.FlitChannel/flitMode (get data :flitMode)
           :cxl_memory.FlitChannel/dataRateGtps (as-double (get data :dataRateGtps))
           :cxl_memory.FlitChannel/createdAt (now)
           :cxl_memory.FlitChannel/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-flit-channels
  "List FlitChannel with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-flit-channels port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :cxl_memory.FlitChannel/id))
         rows (apply-filters rows (:filter opts) [:cxl_memory.FlitChannel/deviceId :cxl_memory.FlitChannel/lanes :cxl_memory.FlitChannel/flitMode :cxl_memory.FlitChannel/dataRateGtps])]
     (paginate rows opts))))

(defn get-flit-channel
  "Retrieve a FlitChannel by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-flit-channel port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-flit-channel
  "Update a FlitChannel; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :deviceId) (conj [:db/add id :cxl_memory.FlitChannel/deviceId (get data :deviceId)]))
                   (cond-> (contains? data :lanes) (conj [:db/add id :cxl_memory.FlitChannel/lanes (as-long (get data :lanes))]))
                   (cond-> (contains? data :flitMode) (conj [:db/add id :cxl_memory.FlitChannel/flitMode (get data :flitMode)]))
                   (cond-> (contains? data :dataRateGtps) (conj [:db/add id :cxl_memory.FlitChannel/dataRateGtps (as-double (get data :dataRateGtps))]))
                   (conj [:db/add id :cxl_memory.FlitChannel/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-flit-channel
  "Delete a FlitChannel."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── CoherenceDomain ────────────────────────────────────────────────────────────────
(defn create-coherence-domain
  "Create a CoherenceDomain."
  [port data]
  (require-fields data ["hostCount" "protocol"])
  (let [id (new-id "cxl_coh")
        e {:db/id id
           :cxl_memory.CoherenceDomain/id id
           :cxl_memory.CoherenceDomain/deviceId (get data :deviceId)
           :cxl_memory.CoherenceDomain/hostCount (as-long (get data :hostCount))
           :cxl_memory.CoherenceDomain/protocol (get data :protocol)
           :cxl_memory.CoherenceDomain/biasMode (get data :biasMode)
           :cxl_memory.CoherenceDomain/createdAt (now)
           :cxl_memory.CoherenceDomain/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-coherence-domains
  "List CoherenceDomain with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-coherence-domains port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :cxl_memory.CoherenceDomain/id))
         rows (apply-filters rows (:filter opts) [:cxl_memory.CoherenceDomain/deviceId :cxl_memory.CoherenceDomain/hostCount :cxl_memory.CoherenceDomain/protocol :cxl_memory.CoherenceDomain/biasMode])]
     (paginate rows opts))))

(defn get-coherence-domain
  "Retrieve a CoherenceDomain by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-coherence-domain port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-coherence-domain
  "Update a CoherenceDomain; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :deviceId) (conj [:db/add id :cxl_memory.CoherenceDomain/deviceId (get data :deviceId)]))
                   (cond-> (contains? data :hostCount) (conj [:db/add id :cxl_memory.CoherenceDomain/hostCount (as-long (get data :hostCount))]))
                   (cond-> (contains? data :protocol) (conj [:db/add id :cxl_memory.CoherenceDomain/protocol (get data :protocol)]))
                   (cond-> (contains? data :biasMode) (conj [:db/add id :cxl_memory.CoherenceDomain/biasMode (get data :biasMode)]))
                   (conj [:db/add id :cxl_memory.CoherenceDomain/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-coherence-domain
  "Delete a CoherenceDomain."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── QosClass ────────────────────────────────────────────────────────────────
(defn create-qos-class
  "Create a QosClass."
  [port data]
  (require-fields data ["name" "bandwidthGbps"])
  (let [id (new-id "cxl_qos")
        e {:db/id id
           :cxl_memory.QosClass/id id
           :cxl_memory.QosClass/deviceId (get data :deviceId)
           :cxl_memory.QosClass/name (get data :name)
           :cxl_memory.QosClass/bandwidthGbps (as-double (get data :bandwidthGbps))
           :cxl_memory.QosClass/latencyNs (as-double (get data :latencyNs))
           :cxl_memory.QosClass/createdAt (now)
           :cxl_memory.QosClass/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-qos-classes
  "List QosClass with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-qos-classes port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :cxl_memory.QosClass/id))
         rows (apply-filters rows (:filter opts) [:cxl_memory.QosClass/deviceId :cxl_memory.QosClass/name :cxl_memory.QosClass/bandwidthGbps :cxl_memory.QosClass/latencyNs])]
     (paginate rows opts))))

(defn get-qos-class
  "Retrieve a QosClass by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-qos-class port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-qos-class
  "Update a QosClass; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :deviceId) (conj [:db/add id :cxl_memory.QosClass/deviceId (get data :deviceId)]))
                   (cond-> (contains? data :name) (conj [:db/add id :cxl_memory.QosClass/name (get data :name)]))
                   (cond-> (contains? data :bandwidthGbps) (conj [:db/add id :cxl_memory.QosClass/bandwidthGbps (as-double (get data :bandwidthGbps))]))
                   (cond-> (contains? data :latencyNs) (conj [:db/add id :cxl_memory.QosClass/latencyNs (as-double (get data :latencyNs))]))
                   (conj [:db/add id :cxl_memory.QosClass/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-qos-class
  "Delete a QosClass."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── HotplugEvent ────────────────────────────────────────────────────────────────
(defn create-hotplug-event
  "Create a HotplugEvent."
  [port data]
  (require-fields data ["kind" "slot"])
  (let [id (new-id "cxl_hot")
        e {:db/id id
           :cxl_memory.HotplugEvent/id id
           :cxl_memory.HotplugEvent/deviceId (get data :deviceId)
           :cxl_memory.HotplugEvent/kind (get data :kind)
           :cxl_memory.HotplugEvent/slot (as-long (get data :slot))
           :cxl_memory.HotplugEvent/status (get data :status)
           :cxl_memory.HotplugEvent/createdAt (now)
           :cxl_memory.HotplugEvent/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-hotplug-events
  "List HotplugEvent with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-hotplug-events port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :cxl_memory.HotplugEvent/id))
         rows (apply-filters rows (:filter opts) [:cxl_memory.HotplugEvent/deviceId :cxl_memory.HotplugEvent/kind :cxl_memory.HotplugEvent/slot :cxl_memory.HotplugEvent/status])]
     (paginate rows opts))))

(defn get-hotplug-event
  "Retrieve a HotplugEvent by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-hotplug-event port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-hotplug-event
  "Update a HotplugEvent; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :deviceId) (conj [:db/add id :cxl_memory.HotplugEvent/deviceId (get data :deviceId)]))
                   (cond-> (contains? data :kind) (conj [:db/add id :cxl_memory.HotplugEvent/kind (get data :kind)]))
                   (cond-> (contains? data :slot) (conj [:db/add id :cxl_memory.HotplugEvent/slot (as-long (get data :slot))]))
                   (cond-> (contains? data :status) (conj [:db/add id :cxl_memory.HotplugEvent/status (get data :status)]))
                   (conj [:db/add id :cxl_memory.HotplugEvent/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-hotplug-event
  "Delete a HotplugEvent."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/cxldevices" :op :create :entity "CxlDevice"}
   {:method "GET" :path "/v1/cxldevices" :op :list :entity "CxlDevice"}
   {:method "GET" :path "/v1/cxldevices/:id" :op :get :entity "CxlDevice"}
   {:method "PATCH" :path "/v1/cxldevices/:id" :op :update :entity "CxlDevice"}
   {:method "DELETE" :path "/v1/cxldevices/:id" :op :delete :entity "CxlDevice"}
   {:method "POST" :path "/v1/memoryregions" :op :create :entity "MemoryRegion"}
   {:method "GET" :path "/v1/memoryregions" :op :list :entity "MemoryRegion"}
   {:method "GET" :path "/v1/memoryregions/:id" :op :get :entity "MemoryRegion"}
   {:method "PATCH" :path "/v1/memoryregions/:id" :op :update :entity "MemoryRegion"}
   {:method "DELETE" :path "/v1/memoryregions/:id" :op :delete :entity "MemoryRegion"}
   {:method "POST" :path "/v1/flitchannels" :op :create :entity "FlitChannel"}
   {:method "GET" :path "/v1/flitchannels" :op :list :entity "FlitChannel"}
   {:method "GET" :path "/v1/flitchannels/:id" :op :get :entity "FlitChannel"}
   {:method "PATCH" :path "/v1/flitchannels/:id" :op :update :entity "FlitChannel"}
   {:method "DELETE" :path "/v1/flitchannels/:id" :op :delete :entity "FlitChannel"}
   {:method "POST" :path "/v1/coherencedomains" :op :create :entity "CoherenceDomain"}
   {:method "GET" :path "/v1/coherencedomains" :op :list :entity "CoherenceDomain"}
   {:method "GET" :path "/v1/coherencedomains/:id" :op :get :entity "CoherenceDomain"}
   {:method "PATCH" :path "/v1/coherencedomains/:id" :op :update :entity "CoherenceDomain"}
   {:method "DELETE" :path "/v1/coherencedomains/:id" :op :delete :entity "CoherenceDomain"}
   {:method "POST" :path "/v1/qosclasses" :op :create :entity "QosClass"}
   {:method "GET" :path "/v1/qosclasses" :op :list :entity "QosClass"}
   {:method "GET" :path "/v1/qosclasses/:id" :op :get :entity "QosClass"}
   {:method "PATCH" :path "/v1/qosclasses/:id" :op :update :entity "QosClass"}
   {:method "DELETE" :path "/v1/qosclasses/:id" :op :delete :entity "QosClass"}
   {:method "POST" :path "/v1/hotplugevents" :op :create :entity "HotplugEvent"}
   {:method "GET" :path "/v1/hotplugevents" :op :list :entity "HotplugEvent"}
   {:method "GET" :path "/v1/hotplugevents/:id" :op :get :entity "HotplugEvent"}
   {:method "PATCH" :path "/v1/hotplugevents/:id" :op :update :entity "HotplugEvent"}
   {:method "DELETE" :path "/v1/hotplugevents/:id" :op :delete :entity "HotplugEvent"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"cxldevices" {:create create-cxl-device :list list-cxl-devices :get get-cxl-device :update update-cxl-device :delete delete-cxl-device}
   "memoryregions" {:create create-memory-region :list list-memory-regions :get get-memory-region :update update-memory-region :delete delete-memory-region}
   "flitchannels" {:create create-flit-channel :list list-flit-channels :get get-flit-channel :update update-flit-channel :delete delete-flit-channel}
   "coherencedomains" {:create create-coherence-domain :list list-coherence-domains :get get-coherence-domain :update update-coherence-domain :delete delete-coherence-domain}
   "qosclasses" {:create create-qos-class :list list-qos-classes :get get-qos-class :update update-qos-class :delete delete-qos-class}
   "hotplugevents" {:create create-hotplug-event :list list-hotplug-events :get get-hotplug-event :update update-hotplug-event :delete delete-hotplug-event}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "cxl_memory-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
